### ISSUE TITLE
Mapa mental Julissa Migdalia José Cruz

### ISSUE THREAD

**Issue by Julissamigdalia** [SistemasTecTlaxiaco/mapa-mental-Julissamigdalia#2]
[Mapa mental, Julissa Migdalia José Cruz.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-Julissamigdalia/files/7274727/Mapa.mental.Julissa.Migdalia.Jose.Cruz.pdf)

**Comment by gilbertovelasco1** [comment]
97 
muy bien solo falto elementos de sistema multimedia

**Comment by gilbertovelasco1** [comment]
17% 
solo sistemas multimedia y clasificación

**Comment by josealfredo79** [comment]
Bien hecho y revisado
